# site settings
title: Jekyll
subtitle: by JOSE
email: jocvegar@gmail.com
description: Just me messing around, building stuff<br /> and learning :).
baseurl: "/forty-jekyll-demo" # the subpath of your site, e.g. /blog
url: "https://jocvegar.github.io"
author: Jose
street_address: Here st.
city: Tegucigalpa
state: FM
zip_code: 11101
country: Hondy
phone: 9999-9999

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url:
github_url: http://github.com/jocvegar
gitlab_url:
googleplus_url:
instagram_url: http://instagram.com/jocvegar
linkedin_url: https://www.linkedin.com/in/jose-carlos-vega/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/joc4

# build settings
markdown: kramdown

sass:
  style: compressed
